### ISSUE TITLE
500内部服务器错误

### ISSUE THREAD

**Issue by cs-usst** [ark930/shanghai-bus#3]
Ubuntu环境下出现500错误，访问网址 127.0.0.1:5000/bus/960路

log:
```
 * Serving Flask app "router"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2019-05-08 11:18:40,751] ERROR in app: Exception on /bus/960路 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asus/Desktop/shanghai-bus-master/router.py", line 32, in query_router
    routers = bus.query_router(router_name, direction)
  File "/home/asus/Desktop/shanghai-bus-master/bus.py", line 132, in query_router
    soup = BeautifulSoup(r.text.encode(r.encoding), 'lxml')
  File "/home/asus/.local/lib/python3.6/site-packages/bs4/__init__.py", line 196, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

```
是编码的问题？还是使用方式不对？
另外windows下出现的是404错误，由于我的windows系统语言是英文的，可能处理路线的时候有问题（尽管我加上了# -*- coding: utf-8 -*-），您知道有什么方法能够解决这个问题吗？
谢谢

**Comment by ark930** [comment]
看最后一行报错信息，应该是没有按照 lxml。运行`pip install lxml` 或者 `pip3 install lxml` 命令试试.

**Comment by ark930** [comment]
试试对请求的参数进行 URL encode
```
$ curl http://127.0.0.1:5000/bus/960%E8%B7%AF
{
  "direction": "0",
  "end_at": "22:30",
  "from": "怀德路杨树浦路",
  "start_at": "05:00",
  "stops": [
    {
      "stop_id": "1.",
      "stop_name": "怀德路杨树浦路"
    },
    {
      "stop_id": "2.",
      "stop_name": "许昌路龙江路"
    },
    {
      "stop_id": "3.",
      "stop_name": "许昌路平凉路"
    },
    {
      "stop_id": "4.",
      "stop_name": "许昌路长阳路"
    },
    {
      "stop_id": "5.",
      "stop_name": "许昌路周家嘴路"
    },
    {
      "stop_id": "6.",
      "stop_name": "许昌路控江路"
    },
    {
      "stop_id": "7.",
      "stop_name": "鞍山路锦西路"
    },
    {
      "stop_id": "8.",
      "stop_name": "同济大学"
    },
    {
      "stop_id": "9.",
      "stop_name": "四平路赤峰路"
    },
    {
      "stop_id": "10.",
      "stop_name": "赤峰路密云路"
    },
    {
      "stop_id": "11.",
      "stop_name": "密云路赤峰路"
    },
    {
      "stop_id": "12.",
      "stop_name": "辉河路中山北二路"
    },
    {
      "stop_id": "13.",
      "stop_name": "松花江路邯郸路"
    },
    {
      "stop_id": "14.",
      "stop_name": "复旦大学"
    },
    {
      "stop_id": "15.",
      "stop_name": "国定路邯郸路"
    },
    {
      "stop_id": "16.",
      "stop_name": "肺科医院"
    },
    {
      "stop_id": "17.",
      "stop_name": "武东路政民路"
    },
    {
      "stop_id": "18.",
      "stop_name": "武东路武川路"
    },
    {
      "stop_id": "19.",
      "stop_name": "武川路政立路"
    },
    {
      "stop_id": "20.",
      "stop_name": "国权北路政立路"
    },
    {
      "stop_id": "21.",
      "stop_name": "国权北路三门路"
    },
    {
      "stop_id": "22.",
      "stop_name": "青石路国权北路"
    }
  ],
  "to": "青石路国权北路"
}
```

**Comment by cs-usst** [comment]
应该就是没有装lxml造成的，谢谢！！

不过我遇到了另一个问题，另开一个issue吧
